export const IPC_CHANNELS = {
  appGetStatus: 'app:get-status',
  settingsGet: 'settings:get',
  settingsUpdate: 'settings:update',
  catalogHome: 'catalog:home',
  catalogSearch: 'catalog:search',
  catalogDetails: 'catalog:details',
  catalogEpisodeDetails: 'catalog:episode-details',
  catalogCancel: 'catalog:cancel',
  watchlistGet: 'watchlist:get',
  watchlistSet: 'watchlist:set',
  integrationsGet: 'integrations:get',
  integrationsUpdate: 'integrations:update',
  integrationsChooseDownloadPath: 'integrations:choose-download-path',
  releasesSearch: 'releases:search',
  releasesDownload: 'releases:download',
  mediaCancel: 'media:cancel',
  torrentsStart: 'torrents:start',
  torrentsStatus: 'torrents:status',
  torrentsControl: 'torrents:control',
  subtitlesSearch: 'subtitles:search',
  subtitlesDownload: 'subtitles:download',
} as const;
